### ISSUE TITLE
Auto ignore files and folders in .gitignore

### ISSUE THREAD

**Issue by xaviervia** [aweary/alder#2]
Hello! Thanks for this.

This is a small feature request, I was running alder in a project that contains a `node_modules` folder and it takes a while, plus it has a lot file I was not interested in listing. I thought it would be nice if by default it would pick up the `.gitignore` file and skip those folders entirely. This would make scanning code project folders a breeze 🌬

If you think this make sense I can try to PR it.

**Comment by aweary** [comment]
That makes a lot of sense! I would be happy to review a PR for it. We could maybe just read and parse the rules in the `.gitignore` and use [ignore](https://www.npmjs.com/package/ignore#usage) to filter files/folders based on those rules.

**Comment by xaviervia** [comment]
I’ll close this issue since we are following up on the PR.
