### ISSUE TITLE
Double -d options in readme

### ISSUE THREAD

**Issue by BenDiuguid** [aweary/alder#7]
Both depth/directories both say they have the shortcut of `-d` but `alder -d 3` returns this error:

```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '${pwd}/3'
   ...
```

It doesn't actually return the string ${pwd} but it does return the current directory/3

**Comment by nitishdayal** [comment]
Suggested fix here: https://github.com/aweary/alder/pull/8
